-- MySQL Script generated by MySQL Workbench
-- Fri Dec 23 02:12:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ServerServiceDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ServerServiceDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ServerServiceDatabase` DEFAULT CHARACTER SET utf8 ;
USE `ServerServiceDatabase` ;

-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`회원정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`회원정보` (
  `회원번호` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  `전화번호` VARCHAR(20) NULL,
  `이메일` VARCHAR(100) NULL,
  `생일` DATE NULL,
  `국가코드` VARCHAR(10) NULL,
  `회원 이미지 저장 경로` VARCHAR(200) NULL,
  `회원 등급` INT NULL DEFAULT 1,
  `정보 변경 날짜` DATETIME NULL,
  `안드로이드SDK레벨` INT NULL DEFAULT 1,
  `핸드폰기종` VARCHAR(200) NULL,
  `회원비활성화` TINYINT(1) NULL,
  PRIMARY KEY (`회원번호`),
  UNIQUE INDEX `회원번호_UNIQUE` (`회원번호` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장정보` (
  `매장번호` INT NOT NULL,
  `주소` VARCHAR(500) NULL,
  `위도` DOUBLE NULL,
  `경도` DOUBLE NULL,
  `이름` VARCHAR(200) NULL,
  `전화번호` VARCHAR(20) NULL,
  `소개글` VARCHAR(1000) NULL,
  `매장 이미지 저장 경로` VARCHAR(200) NULL,
  `국가코드` VARCHAR(10) NULL,
  `서비스 가입 날짜` DATE NULL,
  `정보 변경 날짜` DATETIME NULL,
  `서비스 탈퇴 여부` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`매장번호`),
  UNIQUE INDEX `매장번호_UNIQUE` (`매장번호` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장등록 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장등록 정보` (
  `고유등록번호` INT NOT NULL,
  `회원번호` INT NOT NULL,
  `매장번호` INT NOT NULL,
  `회원탈퇴여부` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`고유등록번호`, `회원번호`, `매장번호`),
  INDEX `fk_매장등록 정보_매장정보1_idx` (`매장번호` ASC),
  INDEX `fk_매장등록 정보_회원정보1_idx` (`회원번호` ASC),
  UNIQUE INDEX `고유등록번호_UNIQUE` (`고유등록번호` ASC),
  UNIQUE INDEX `회원번호_UNIQUE` (`회원번호` ASC),
  UNIQUE INDEX `매장번호_UNIQUE` (`매장번호` ASC),
  CONSTRAINT `fk_매장등록 정보_회원정보1`
    FOREIGN KEY (`회원번호`)
    REFERENCES `ServerServiceDatabase`.`회원정보` (`회원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_매장등록 정보_매장정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장등록 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장등록 로그` (
  `고유등록번호` INT NOT NULL,
  `변경날짜` DATETIME NULL,
  UNIQUE INDEX `고유등록번호_UNIQUE` (`고유등록번호` ASC),
  CONSTRAINT `fk_매장등록 로그_매장등록 정보1`
    FOREIGN KEY (`고유등록번호`)
    REFERENCES `ServerServiceDatabase`.`매장등록 정보` (`고유등록번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`마일리지 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`마일리지 로그` (
  `고유등록번호` INT NOT NULL,
  `회원번호` INT NOT NULL,
  `매장번호` INT NOT NULL,
  `마일리지 변동 량` INT NULL DEFAULT 0,
  `변경 날짜` DATETIME NOT NULL,
  PRIMARY KEY (`고유등록번호`, `회원번호`, `매장번호`, `변경 날짜`),
  UNIQUE INDEX `고유등록번호_UNIQUE` (`고유등록번호` ASC),
  CONSTRAINT `fk_마일리지 로그_매장등록 정보1`
    FOREIGN KEY (`고유등록번호` , `회원번호` , `매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장등록 정보` (`고유등록번호` , `회원번호` , `매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장공지 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장공지 정보` (
  `매장번호` INT NOT NULL,
  `제목` VARCHAR(2000) NULL,
  `내용` VARCHAR(2000) NULL,
  `공지 시작 날짜` DATE NULL,
  `공지 마감 날짜` DATE NULL,
  `마지막 편집 날짜` DATETIME NULL,
  `이미지 저장 경로` VARCHAR(200) NULL,
  `삭제 여부` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`매장번호`),
  UNIQUE INDEX `매장번호_UNIQUE` (`매장번호` ASC),
  CONSTRAINT `fk_매장공지 정보_매장정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장쿠폰등록정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장쿠폰등록정보` (
  `매장번호` INT NOT NULL,
  `쿠폰고유번호` DATETIME NOT NULL,
  `제목` VARCHAR(2000) NULL,
  `내용` VARCHAR(2000) NULL,
  `쿠폰모양코드` INT NOT NULL,
  `삭제 여부` TINYINT(1) NULL,
  PRIMARY KEY (`매장번호`, `쿠폰고유번호`),
  UNIQUE INDEX `매장번호_UNIQUE` (`매장번호` ASC),
  UNIQUE INDEX `쿠폰고유번호_UNIQUE` (`쿠폰고유번호` ASC),
  UNIQUE INDEX `쿠폰모양코드_UNIQUE` (`쿠폰모양코드` ASC),
  CONSTRAINT `fk_매장쿠폰등록정보_매장정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`업로더 위치 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`업로더 위치 정보` (
  `매장번호` INT NOT NULL,
  `업로드 위치 위도` DOUBLE NULL,
  `업로드 위치 경도` DOUBLE NULL,
  `업로드 날짜` DATETIME NOT NULL,
  CONSTRAINT `fk_업로더 위치 정보_매장공지 정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장공지 정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_업로더 위치 정보_매장쿠폰등록정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장쿠폰등록정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`쿠폰모양 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`쿠폰모양 정보` (
  `쿠폰모양코드` INT NOT NULL,
  `쿠폰 이미지 저장 경로` VARCHAR(200) NULL,
  `쿠폰 모양 가격` INT NULL,
  `사용 제한 기간` INT NULL,
  `쿠폰 모양 설명` VARCHAR(2000) NULL,
  UNIQUE INDEX `쿠폰모양코드_UNIQUE` (`쿠폰모양코드` ASC),
  CONSTRAINT `fk_쿠폰모양 정보_매장쿠폰등록정보2`
    FOREIGN KEY (`쿠폰모양코드`)
    REFERENCES `ServerServiceDatabase`.`매장쿠폰등록정보` (`쿠폰모양코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장 쿠폰 모양 수집 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장 쿠폰 모양 수집 로그` (
  `매장번호` INT NOT NULL,
  `쿠폰모양코드` INT NOT NULL,
  `변경 날짜` DATETIME NULL,
  CONSTRAINT `fk_매장 쿠폰 모양 수집 로그_매장정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_매장 쿠폰 모양 수집 로그_쿠폰모양 정보2`
    FOREIGN KEY (`쿠폰모양코드`)
    REFERENCES `ServerServiceDatabase`.`쿠폰모양 정보` (`쿠폰모양코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장 쿠폰 사용 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장 쿠폰 사용 로그` (
  `고유등록번호` INT NOT NULL,
  `변경 날짜` DATETIME NULL,
  `사용 여부` TINYINT(1) NULL DEFAULT 0,
  `쿠폰고유번호` DATETIME NOT NULL,
  INDEX `fk_매장 쿠폰 사용 로그_매장쿠폰등록정보1_idx` (`쿠폰고유번호` ASC),
  UNIQUE INDEX `고유등록번호_UNIQUE` (`고유등록번호` ASC),
  UNIQUE INDEX `쿠폰고유번호_UNIQUE` (`쿠폰고유번호` ASC),
  CONSTRAINT `fk_매장 쿠폰 사용 로그_매장등록 정보1`
    FOREIGN KEY (`고유등록번호`)
    REFERENCES `ServerServiceDatabase`.`매장등록 정보` (`고유등록번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_매장 쿠폰 사용 로그_매장쿠폰등록정보1`
    FOREIGN KEY (`쿠폰고유번호`)
    REFERENCES `ServerServiceDatabase`.`매장쿠폰등록정보` (`쿠폰고유번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`사용자 위치 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`사용자 위치 정보` (
  `고유등록번호` INT NOT NULL,
  `사용자 위치 위도` DOUBLE NULL,
  `사용자 위치 경도` DOUBLE NULL,
  `변경 날짜` DATETIME NOT NULL,
  CONSTRAINT `fk_사용자 위치 정보_마일리지 로그1`
    FOREIGN KEY (`고유등록번호`)
    REFERENCES `ServerServiceDatabase`.`마일리지 로그` (`고유등록번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_사용자 위치 정보_매장 쿠폰 사용 로그1`
    FOREIGN KEY (`고유등록번호`)
    REFERENCES `ServerServiceDatabase`.`매장 쿠폰 사용 로그` (`고유등록번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`매장 제품 정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`매장 제품 정보` (
  `매장번호` INT NOT NULL,
  `제품코드` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  `원가` INT NULL,
  `판매가` INT NULL,
  `잔존가` INT NULL,
  `등록일` DATE NULL,
  `변경 날짜` DATETIME NULL,
  `사용여부` TINYINT(1) NULL,
  PRIMARY KEY (`매장번호`, `제품코드`),
  UNIQUE INDEX `매장번호_UNIQUE` (`매장번호` ASC),
  UNIQUE INDEX `제품코드_UNIQUE` (`제품코드` ASC),
  CONSTRAINT `fk_매장 제품 정보_매장정보1`
    FOREIGN KEY (`매장번호`)
    REFERENCES `ServerServiceDatabase`.`매장정보` (`매장번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`피드백 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`피드백 로그` (
  `회원번호` INT NOT NULL,
  `태그 아이디` INT NOT NULL,
  `전송 날짜` DATETIME NOT NULL,
  `내용` VARCHAR(500) NULL,
  PRIMARY KEY (`회원번호`, `전송 날짜`),
  UNIQUE INDEX `태그 아이디_UNIQUE` (`태그 아이디` ASC),
  CONSTRAINT `fk_피드백 로그_회원정보1`
    FOREIGN KEY (`회원번호`)
    REFERENCES `ServerServiceDatabase`.`회원정보` (`회원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`태그 로그`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`태그 로그` (
  `태그 아이디` INT NOT NULL,
  `태그 내용` VARCHAR(45) NULL,
  CONSTRAINT `fk_태그 로그_피드백 로그1`
    FOREIGN KEY (`태그 아이디`)
    REFERENCES `ServerServiceDatabase`.`피드백 로그` (`태그 아이디`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`제품 최적 재고량`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`제품 최적 재고량` (
  `제품코드` INT NOT NULL,
  `사용된 엔진 버전` INT NULL,
  `최적 재고량` INT NULL,
  `날짜` DATE NULL,
  CONSTRAINT `fk_제품 최적 재고량_매장 제품 정보2`
    FOREIGN KEY (`제품코드`)
    REFERENCES `ServerServiceDatabase`.`매장 제품 정보` (`제품코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServerServiceDatabase`.`제품 판매량`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServerServiceDatabase`.`제품 판매량` (
  `제품코드` INT NOT NULL,
  `판매량` INT NULL,
  `날짜` DATE NULL,
  `에상 판매량` INT NULL,
  CONSTRAINT `fk_제품 판매량_매장 제품 정보2`
    FOREIGN KEY (`제품코드`)
    REFERENCES `ServerServiceDatabase`.`매장 제품 정보` (`제품코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
